Merging ShelfLife conversion into release branch for QA.
Rinchem-ChemStar/IntelShelfLife pull request #1
Opened 2021-06-18 16:15 UTC by eddieSkywalker90

For any notes on changes see commits.

2021-06-22 20:34 UTC, Chem-Star requested changes
Let's change the repo name to IntelShelfLife so we can easily identify/group code by the customer that it is running for.

As always feel free to disagree with anything and let me know if you want to hop on a call to talk through anything. 

One general note, I would like to see more trace or debug logging used so that we have a better chance to diagnose production issues if they happen to arise.

Overall, I thought the structure was pretty solid and a decent bit cleaner than Intel Inventory Export.

2021-06-24 16:13 UTC, eddieSkywalker90 commented on ShelfLife/Configuration.cs
> +        public static readonly UserSettings Settings = new(Initialize());
Code section removed due to removal of Jank.Config NuGet pkg.

2021-06-24 16:20 UTC, eddieSkywalker90 commented on ShelfLife/Configuration.cs
> +            var environmentName = System.Environment.GetEnvironmentVariable(".NET_ENVIRONMENT");
Changes made.

2021-06-24 17:44 UTC, eddieSkywalker90 commented on ShelfLife/Program.cs
> +                Log.Information(e, Configuration.FailMessage);
Created nested TryCatch around the process functionality, so any exceptions brought up here are handled as previously, and then thrown into a finishing handler, InvalidCredentialException().

This has separated the initial logger and ProgramStatusDb connection code from the process code. The ProgramStatusController already has error handling inside it, so after it is handled within (as previously written), I throw it up to the same finishing handler, InvalidCredentialException(), to flush out the Logger.

Original most outer TryCatch now captures the Logger individually, and I've removed Logging from the Catch clause. Simple WriteToConsole happens now if this fails. With the expectation the user turning this app on would see immediately see.

2021-06-24 17:49 UTC, eddieSkywalker90 commented on ShelfLife/Program.cs
> +                Log.Information(e, Configuration.FailMessage);
Added new appSettings variable LoggerFailure for the message string.

2021-06-24 18:08 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +        private int RetrieveNextFileNumber(ProgramStatusDbContext dbContext)
Changes made.

- Deleted EntryNumber from ShelfLifeModel class.
- Repointed Program.StatusController.ShelfLifeModel() variable to now point at .Id when it is looking at the ShelfLifeModel object.
- Repointed Program.StatusController.FinishSuccessfulLogAttempt() variable to now point at .Id when it is looking at the ShelfLifeModel object.
- Repointed Program.StatusController.RetrieveNextFileNum() variable to now point at num.Id 
-- Before deleting the EntryNum column I tested to make sure current index was matching Id value.

2021-06-24 18:14 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +        public void SendErrorMessage(string errorMessage)
Makes sense. Approved!

2021-06-24 18:39 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeController.cs
> +        public async Task<List<ShelfLifeModel>> ReturnModifiedDataAsync(string storedProcedure)
Changes made, renamed with Get instead.

2021-06-24 18:53 UTC, eddieSkywalker90 commented on ShelfLife/Program.cs
> +            }
I believe they have to stay. There is 3 uses of the Flusher, 1 documented in this comment, and the other 2 are also in Program but are not apart of an Exception so they wouldn't be caught with the Exception Flusher.

I think the only way to use single flush is by adding another nested TryCatch to separate the ProgramStatusController and Log.Logger and then using a Finally block.

Oh, but I can eliminate 1 of them.

- Moved both flushes out of the If/Else and placed single flush after the If/Else.

2021-06-24 18:54 UTC, eddieSkywalker90 commented on ShelfLife/Properties/launchSettings.json
> +{
Added to GitIgnore.

2021-06-24 19:24 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeController.cs
> +                {
Nice! Good catch. Changes tested and made.

- Only correction I made to above is count == batchSize. Ignoring the - 1 since count matches direct amount in batch (i.e. at IF-Statement it will already be 4 when there's indeed 4).
- Reduced to single renamed method called SendBatch(). 
- There is a 250ms delay after final batch is sent but I see this as negligible and OK to have.

2021-06-24 19:34 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeWebServiceController.cs
> +                    Timeout = -1
Removed Timeout setting since it seems it has its own default value of 100s. Googled online and found a consensus that RestSharp uses HttpWebRequest whos default Timeout is 100s.
https://stackoverflow.com/questions/28829524/what-is-default-timeout-value-of-restsharp-restclient/28855824

Let me know if you want one there anyway set to 120.

2021-06-24 19:35 UTC, eddieSkywalker90 commented on ShelfLife/appsettings.Development.json
> +  "exclude": [
Added to GitIgnore

2021-06-24 19:40 UTC, eddieSkywalker90 commented on ShelfLife/appsettings.json
> +  "exclude": [
I ...don't really know. It gets set by default.
https://stackoverflow.com/questions/61739350/in-appsettings-production-json-what-is-the-exclude-section
This is all I found online. A simple answer that I understand, but also do not understand lol.

I'm going to remove it.

2021-06-24 19:41 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeXmlBuilder.cs
> +                ns: Configuration.SoapEnv);
Good to know, they are ugly.

2021-06-24 20:44 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +            CreateLogAttempt();
Considered.

* I'd like to keep class name as ProgramStatusController, I think it better represents an object with duties to interact with ProgramStatus. 
  * However, I did not like the **FinishSuccessfulLogAttempt**() method name, so I renamed this to **RecordSuccess**() I think this definitely shortens the name length, and follows same pattern as comment below. 
  * I also renamed **CreateLogAttempt**() to **CreateLog**(). Looking at it, I don't see any need for 'attempt' in the name since in normal running conditions it should be working and just creating logs. (I think attempt probably better lingo for a comment)

2021-06-25 00:17 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeWebServiceController.cs
> +                var response = client.Execute(request);
* Added code so that SOAP message + Response get logged to a separate WebServiceLog file whos path is determined in appSettings same as standard Log path.
* In Program.cs the logger is defined in 3 lines, with Info + Error type logs going to the same directory (although individually changeable), with Fatal types being a separate file used for WebService issues noted in first bullet.
* This took SOOOO much longer than I thought.

2021-06-25 16:14 UTC, eddieSkywalker90 commented on ShelfLife/Program.cs
> +                Log.Logger = new LoggerConfiguration().WriteTo.File(logsFilePath, rollingInterval: RollingInterval.Day).CreateLogger();
Info level + above

2021-06-25 16:46 UTC, Chem-Star commented on ShelfLife/ShelfLife/ShelfLifeWebServiceController.cs
> +                    Timeout = -1
Good with the 100s timeout

2021-06-25 16:52 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +                    Timestamp = DateTime.Now,
CreateAtUtc and UpdatedAtUtc will be the variable names used

2021-06-25 16:54 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +                latestStatusEntry[0].Timestamp = DateTime.Now.ToUniversalTime();
Speaking with Jason, it was the piece of code that generates the initial timestamp that set the time to NON-UTC. That time needs to also be UTC.

2021-06-25 18:11 UTC, eddieSkywalker90 commented on ShelfLife/Program.cs
> +                Log.Logger = new LoggerConfiguration().WriteTo.File(logsFilePath, rollingInterval: RollingInterval.Day).CreateLogger();
Added Serilog.Console package to add WriteTo.Console to the general (Info and higher) logs file that was reworked and implemented per a convo below.

2021-06-25 18:14 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +                latestStatusEntry[0].Timestamp = DateTime.Now.ToUniversalTime();
Changes made below:

ProgramStatusController.cs
- CreateLog()
  - Changed Timestamp to be set to DateTime.Now.ToUniversalTime() to match the same time setting as called in RecordSuccess method in same class. The CreateLog time was setting just DateTime.Now putting in the improper time, and if the program failed to update you would see the incorrect time logged.

2021-06-25 19:00 UTC, eddieSkywalker90 commented on ShelfLife/ProgramStatus/ProgramStatusController.cs
> +                    Timestamp = DateTime.Now,
- Added Migration to add 2 columns CreatedAtUtc + UpdatedAtUtc and delete Timestamp.
   - The migration performs a RENAME column in Timestamp and transfers it to CreatedAtUtc. This will not drop the original column data.

2021-06-25 19:46 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeWebServiceController.cs
> +                var response = client.Execute(request);
* Reimplemented Logger to use 2 Minimum.levels of logging: Debug + Info. One file will log all logs Debug and above, the other will remain high level logging of Info level and above.
* Added Log.Debug periodically throughout program to be able to see program flow.

2021-06-25 20:34 UTC, eddieSkywalker90 commented on ShelfLife/ShelfLife/ShelfLifeWebServiceController.cs
> +                var response = client.Execute(request);
Added arguments for the Logs to only last 5 days.

2021-06-29 19:52 UTC, Chem-Star commented
Need to update process to route based on so_f 9.2/9,9 flag. See reference doc: https://drive.google.com/file/d/1Vyjtkf_YmQackQLgT0HvaYajUOI_JXZy/view?usp=sharing

2021-07-27 15:47 UTC, Chem-Star approved these changes

2021-07-27 15:49 UTC, merged